import './style.css';
import * as pdfjsLib from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
pdfjsLib.GlobalWorkerOptions.workerSrc = workerUrl;

const app=document.querySelector('#app');
app.innerHTML=`<header><b>PDF Editor V4</b><span class="sub">Click fields and text directly • browser-only</span><label class="open">Open PDF<input id="pdfInput" type="file" accept="application/pdf" hidden></label><button id="save" disabled>Save PDF</button></header>
<div class="shell"><aside>
<button data-tool="edit" class="active">↖ Edit existing</button><button data-tool="text">T Add text</button><button data-tool="whiteout">▭ Whiteout</button><button data-tool="rect">□ Box</button><button data-tool="check">✓ Check / X</button>
<button id="addImage">▧ Signature / image</button><input id="imageInput" type="file" accept="image/png,image/jpeg" hidden>
<hr><b>Editing</b><label class="switch"><input id="existingText" type="checkbox" checked> Existing text clickable</label><label class="switch"><input id="nativeFields" type="checkbox" checked> Native form fields</label><div id="info" class="mini">Open a PDF.</div>
<hr><b>Signature presets</b><div id="presets"></div><button id="savePreset">+ Save signature preset</button>
<hr><button id="delete">Delete selected</button><button id="undo">Undo last</button>
<div class="help"><b>Edit existing text:</b> choose Edit existing, then click the words. An input appears over that exact area. Type and press Enter.<br><br><b>Real PDF fields:</b> text boxes, checkboxes, radio buttons and dropdowns are interactive directly.<br><br><b>Printed empty boxes:</b> use Add text or Check / X and click inside the box.</div>
</aside><main><div id="empty"><h2>Open a PDF</h2><p>Edit fields directly, click printed text to replace it, or add signatures and annotations.</p></div><div id="stageWrap" hidden><div id="stage"><canvas id="pdfCanvas"></canvas><div id="interaction"></div><div id="overlay"></div></div></div></main></div>
<footer><button id="prev">←</button><span id="pageInfo">No PDF</span><button id="next">→</button><button id="zoomOut">−</button><span id="zoomLabel">100%</span><button id="zoomIn">+</button></footer>`;
const $=s=>document.querySelector(s);let pdf=null,pdfBytes=null,pageNum=1,zoom=1.15,objects=[],selected=null,tool='edit',pageData=new Map(),formEdits=new Map(),token=0;
const stage=$('#stage'),canvas=$('#pdfCanvas'),interaction=$('#interaction'),overlay=$('#overlay');
const esc=s=>(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const pageObjects=()=>objects.filter(o=>o.page===pageNum);
function select(el){document.querySelectorAll('.obj.selected').forEach(x=>x.classList.remove('selected'));selected=el;if(el)el.classList.add('selected')}
async function inspectPage(page,vp){const tc=await page.getTextContent(),anns=await page.getAnnotations({intent:'display'});const pieces=[];for(const item of tc.items){if(!item.str?.trim())continue;const tx=pdfjsLib.Util.transform(vp.transform,item.transform),fontPx=Math.max(7,Math.hypot(tx[2],tx[3]));pieces.push({str:item.str,x:tx[4],y:tx[5]-fontPx,w:Math.max(3,item.width*zoom),h:fontPx*1.12,fontSize:fontPx/zoom});}
// Merge adjacent PDF text pieces on the same baseline so clicks feel like Acrobat lines/fields.
pieces.sort((a,b)=>Math.abs(a.y-b.y)<3?a.x-b.x:a.y-b.y);const lines=[];for(const p of pieces){let last=lines.at(-1);if(last&&Math.abs(last.y-p.y)<Math.max(3,p.h*.25)&&p.x-(last.x+last.w)<Math.max(14,p.h*1.2)){last.str+=(p.x-(last.x+last.w)>2?' ':'')+p.str;last.w=Math.max(last.w,p.x+p.w-last.x);last.h=Math.max(last.h,p.h);last.fontSize=Math.max(last.fontSize,p.fontSize)}else lines.push({...p});}
const fields=anns.filter(a=>a.subtype==='Widget').map(a=>{const r=vp.convertToViewportRectangle(a.rect);return{id:a.id,name:a.fieldName||'',type:a.fieldType||'',value:a.fieldValue??'',options:a.options||[],checkBox:!!a.checkBox,radioButton:!!a.radioButton,buttonValue:a.buttonValue||a.exportValue||'',x:Math.min(r[0],r[2]),y:Math.min(r[1],r[3]),w:Math.abs(r[2]-r[0]),h:Math.abs(r[3]-r[1])}});pageData.set(pageNum,{lines,fields});}
async function render(){if(!pdf)return;const t=++token,page=await pdf.getPage(pageNum),vp=page.getViewport({scale:zoom});if(t!==token)return;canvas.width=vp.width;canvas.height=vp.height;for(const e of [canvas,interaction,overlay,stage]){e.style.width=vp.width+'px';e.style.height=vp.height+'px'}await page.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise;await inspectPage(page,vp);drawInteraction();drawObjects();$('#pageInfo').textContent=`Page ${pageNum} / ${pdf.numPages}`;$('#zoomLabel').textContent=Math.round(zoom/1.15*100)+'%'}
function drawInteraction(){interaction.innerHTML='';const d=pageData.get(pageNum)||{lines:[],fields:[]};$('#info').textContent=`${d.lines.length} editable text areas • ${d.fields.length} native fields`;
if($('#existingText').checked)d.lines.forEach((x,i)=>{const hit=document.createElement('button');hit.className='textHit';hit.title='Click to edit: '+x.str;Object.assign(hit.style,{left:x.x+'px',top:x.y+'px',width:Math.max(8,x.w)+'px',height:Math.max(10,x.h)+'px'});hit.onclick=e=>{e.stopPropagation();if(tool==='edit')editLine(x,i)};interaction.appendChild(hit)});
if($('#nativeFields').checked)d.fields.forEach(drawField)}
function editLine(x,i){let o=objects.find(o=>o.type==='replaceText'&&o.page===pageNum&&o.sourceIndex===i);if(!o)o=addObj('replaceText',x.x/zoom,x.y/zoom,{w:Math.max(45,x.w/zoom),h:Math.max(15,x.h/zoom),fontSize:Math.max(7,x.fontSize),text:x.str,sourceIndex:i});const el=overlay.querySelector(`[data-id="${o.id}"]`);select(el);const input=el?.querySelector('input');if(input){input.focus();input.select()}}
const fkey=f=>`${pageNum}:${f.name||f.id}`;
function drawField(f){const key=fkey(f),current=formEdits.has(key)?formEdits.get(key):f.value;let el;if(f.type==='Btn'&&f.radioButton){el=document.createElement('input');el.type='radio';el.className='nativeField radio';el.name='radio_'+(f.name||f.id);el.checked=String(current)===String(f.buttonValue)||current===true;el.onchange=()=>{if(el.checked)formEdits.set(key,f.buttonValue||'Yes')}}else if(f.type==='Btn'){el=document.createElement('input');el.type='checkbox';el.className='nativeField checkbox';el.checked=!!current&&current!=='Off';el.onchange=()=>formEdits.set(key,el.checked)}else if(f.type==='Ch'&&f.options?.length){el=document.createElement('select');el.className='nativeField';for(const op of f.options){const opt=document.createElement('option');opt.value=op.exportValue??op.displayValue??op;opt.textContent=op.displayValue??op.exportValue??op;el.appendChild(opt)}el.value=current||'';el.onchange=()=>formEdits.set(key,el.value)}else{el=document.createElement('input');el.type='text';el.className='nativeField';el.value=current||'';el.oninput=()=>formEdits.set(key,el.value)}el.title=f.name||'PDF field';Object.assign(el.style,{left:f.x+'px',top:f.y+'px',width:Math.max(12,f.w)+'px',height:Math.max(12,f.h)+'px'});interaction.appendChild(el)}
function addObj(type,x=60,y=60,extra={}){const o={id:crypto.randomUUID(),page:pageNum,type,x,y,w:(type==='text'||type==='replaceText')?170:type==='image'?140:36,h:(type==='text'||type==='replaceText')?28:type==='image'?60:30,fontSize:16,...extra};objects.push(o);const el=createObj(o);select(el);return o}
function drawObjects(){overlay.innerHTML='';selected=null;pageObjects().forEach(createObj)}
function createObj(o){const el=document.createElement('div');el.className='obj '+o.type;el.dataset.id=o.id;Object.assign(el.style,{left:o.x*zoom+'px',top:o.y*zoom+'px',width:o.w*zoom+'px',height:o.h*zoom+'px'});if(o.type==='text'||o.type==='replaceText'){el.innerHTML=`<input class="inlineText" value="${esc(o.text)}"><i class="handle"></i>`;el.style.fontSize=o.fontSize*zoom+'px'}else if(o.type==='whiteout'||o.type==='rect')el.innerHTML='<i class="handle"></i>';else if(o.type==='check'){el.innerHTML='<span>✓</span><i class="handle"></i>';el.style.fontSize=o.fontSize*zoom+'px'}else if(o.type==='image')el.innerHTML=`<img src="${o.src}"><i class="handle"></i>`;overlay.appendChild(el);wire(el,o);return el}
function wire(el,o){const input=el.querySelector('.inlineText');if(input){input.oninput=()=>o.text=input.value;input.onfocus=()=>select(el);input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();input.blur()}}}
el.addEventListener('pointerdown',e=>{if(e.target.matches('input,.handle'))return;select(el);let sx=e.clientX,sy=e.clientY,ox=o.x,oy=o.y;el.setPointerCapture(e.pointerId);const mv=v=>{o.x=ox+(v.clientX-sx)/zoom;o.y=oy+(v.clientY-sy)/zoom;el.style.left=o.x*zoom+'px';el.style.top=o.y*zoom+'px'},up=()=>{el.removeEventListener('pointermove',mv);el.removeEventListener('pointerup',up)};el.addEventListener('pointermove',mv);el.addEventListener('pointerup',up)});const h=el.querySelector('.handle');h?.addEventListener('pointerdown',e=>{e.stopPropagation();select(el);let sx=e.clientX,sy=e.clientY,ow=o.w,oh=o.h;h.setPointerCapture(e.pointerId);const mv=v=>{o.w=Math.max(12,ow+(v.clientX-sx)/zoom);o.h=Math.max(12,oh+(v.clientY-sy)/zoom);el.style.width=o.w*zoom+'px';el.style.height=o.h*zoom+'px'},up=()=>{h.removeEventListener('pointermove',mv);h.removeEventListener('pointerup',up)};h.addEventListener('pointermove',mv);h.addEventListener('pointerup',up)})}
overlay.addEventListener('pointerdown',e=>{if(e.target!==overlay)return;select(null);const r=overlay.getBoundingClientRect(),x=(e.clientX-r.left)/zoom,y=(e.clientY-r.top)/zoom;if(tool==='text'){const o=addObj('text',x,y,{text:''});setTimeout(()=>overlay.querySelector(`[data-id="${o.id}"] input`)?.focus())}else if(tool==='whiteout')addObj('whiteout',x,y,{w:150,h:26});else if(tool==='rect')addObj('rect',x,y,{w:150,h:38});else if(tool==='check')addObj('check',x,y,{w:26,h:26,fontSize:22})});
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));overlay.style.pointerEvents=tool==='edit'?'none':'auto';interaction.classList.toggle('editing',tool==='edit')});overlay.style.pointerEvents='none';interaction.classList.add('editing');
$('#existingText').onchange=drawInteraction;$('#nativeFields').onchange=drawInteraction;
$('#pdfInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;pdfBytes=new Uint8Array(await f.arrayBuffer());pdf=await pdfjsLib.getDocument({data:pdfBytes.slice()}).promise;pageNum=1;objects=[];formEdits.clear();pageData.clear();$('#empty').hidden=true;$('#stageWrap').hidden=false;$('#save').disabled=false;render()};
$('#prev').onclick=()=>{if(pdf&&pageNum>1){pageNum--;render()}};$('#next').onclick=()=>{if(pdf&&pageNum<pdf.numPages){pageNum++;render()}};$('#zoomIn').onclick=()=>{if(pdf){zoom=Math.min(2.5,zoom+.15);render()}};$('#zoomOut').onclick=()=>{if(pdf){zoom=Math.max(.5,zoom-.15);render()}};$('#delete').onclick=()=>{if(!selected)return;objects=objects.filter(o=>o.id!==selected.dataset.id);selected.remove();selected=null};$('#undo').onclick=()=>{if(objects.length){objects.pop();drawObjects()}};
const dataURL=file=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});async function addImageFile(file){const src=await dataURL(file),img=new Image();img.onload=()=>{let w=150,h=w*img.height/img.width;if(h>110){h=110;w=h*img.width/img.height}addObj('image',60,60,{src,w,h})};img.src=src}$('#addImage').onclick=()=>$('#imageInput').click();$('#imageInput').onchange=e=>{if(e.target.files[0])addImageFile(e.target.files[0]);e.target.value=''};
function presets(){try{return JSON.parse(localStorage.getItem('pdf-sign-presets')||'[]')}catch{return[]}}function showPresets(){const p=presets();$('#presets').innerHTML=p.length?p.map((x,i)=>`<div class="preset"><button data-p="${i}">${esc(x.name)}</button><button data-d="${i}">×</button></div>`).join(''):'<small>No saved presets</small>';document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{const x=presets()[+b.dataset.p],img=new Image();img.onload=()=>{let w=150,h=w*img.height/img.width;addObj('image',60,60,{src:x.src,w,h})};img.src=x.src});document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{const a=presets();a.splice(+b.dataset.d,1);localStorage.setItem('pdf-sign-presets',JSON.stringify(a));showPresets()})}$('#savePreset').onclick=()=>{const i=document.createElement('input');i.type='file';i.accept='image/png,image/jpeg';i.onchange=async()=>{if(!i.files[0])return;const name=prompt('Preset name:',i.files[0].name.replace(/\.[^.]+$/,''));if(!name)return;const a=presets();a.push({name,src:await dataURL(i.files[0])});localStorage.setItem('pdf-sign-presets',JSON.stringify(a));showPresets()};i.click()};showPresets();
async function applyFields(doc){let form;try{form=doc.getForm()}catch{return}for(const [key,val] of formEdits){const name=key.slice(key.indexOf(':')+1);let f;try{f=form.getField(name)}catch{continue}try{const n=f.constructor.name;if(n.includes('CheckBox'))val?f.check():f.uncheck();else if(n.includes('RadioGroup'))f.select(String(val));else if(n.includes('Dropdown')||n.includes('OptionList'))f.select(String(val));else if(n.includes('TextField'))f.setText(String(val))}catch(e){console.warn(name,e)}}try{form.updateFieldAppearances(await doc.embedFont(StandardFonts.Helvetica))}catch{}}
$('#save').onclick=async()=>{if(!pdfBytes)return;const doc=await PDFDocument.load(pdfBytes),font=await doc.embedFont(StandardFonts.Helvetica);await applyFields(doc);for(const o of objects){const p=doc.getPage(o.page-1),H=p.getHeight();if(o.type==='whiteout'||o.type==='replaceText')p.drawRectangle({x:o.x,y:H-o.y-o.h,width:o.w,height:o.h,color:rgb(1,1,1)});if(o.type==='rect')p.drawRectangle({x:o.x,y:H-o.y-o.h,width:o.w,height:o.h,borderColor:rgb(0,0,0),borderWidth:1});if(o.type==='text'||o.type==='replaceText')p.drawText(o.text||'',{x:o.x,y:H-o.y-o.fontSize,size:o.fontSize,font,color:rgb(0,0,0),maxWidth:o.w,lineHeight:o.fontSize*1.1});if(o.type==='check')p.drawText('X',{x:o.x+3,y:H-o.y-o.fontSize,size:o.fontSize,font,color:rgb(0,0,0)});if(o.type==='image'){const bytes=await fetch(o.src).then(r=>r.arrayBuffer());let im;try{im=await doc.embedPng(bytes)}catch{im=await doc.embedJpg(bytes)}p.drawImage(im,{x:o.x,y:H-o.y-o.h,width:o.w,height:o.h})}}const out=await doc.save(),blob=new Blob([out],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='edited.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
window.addEventListener('keydown',e=>{if((e.key==='Delete'||e.key==='Backspace')&&selected&&!['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();$('#delete').click()}});
