import './style.css';
import * as pdfjsLib from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
pdfjsLib.GlobalWorkerOptions.workerSrc = workerUrl;

const app=document.querySelector('#app');
app.innerHTML=`
<header><b>PDF Editor V3</b><span class="sub">Browser-only • edit detected PDF text & form fields</span><label class="open">Open PDF<input id="pdfInput" type="file" accept="application/pdf" hidden></label><button id="save" disabled>Save PDF</button></header>
<div class="shell"><aside>
 <button data-tool="select" class="active">↖ Select / edit</button><button data-tool="text">T Add text</button><button data-tool="whiteout">▭ Whiteout</button><button data-tool="rect">□ Rectangle</button><button data-tool="check">✓ Checkmark</button>
 <button id="addImage">▧ Add image/signature</button><input id="imageInput" type="file" accept="image/png,image/jpeg" hidden>
 <hr><b>Detected content</b><label class="switch"><input id="showText" type="checkbox" checked> Click existing text to edit</label><label class="switch"><input id="showFields" type="checkbox" checked> Show form fields</label>
 <div id="detectInfo" class="mini">Open a PDF to scan its page.</div>
 <hr><b>Signature presets</b><div id="presets"></div><button id="savePreset">+ Save image as preset</button>
 <hr><button id="delete">Delete selected</button><button id="undo">Undo last</button>
 <div class="help"><b>Existing text:</b> click highlighted text, type replacement, Enter. The original is covered on export.<br><br><b>PDF forms:</b> type/tick directly in blue fields. Form values are saved natively.<br><br>Scanned-image text cannot be directly detected.</div>
</aside><main><div id="empty"><h2>Open any PDF</h2><p>Click detected text to replace it, edit real PDF form fields, or add your own content.</p></div><div id="stageWrap" hidden><div id="stage"><canvas id="pdfCanvas"></canvas><div id="detected"></div><div id="overlay"></div></div></div></main></div>
<footer><button id="prev">←</button><span id="pageInfo">No PDF</span><button id="next">→</button><button id="zoomOut">−</button><span id="zoomLabel">100%</span><button id="zoomIn">+</button></footer>`;
const $=s=>document.querySelector(s); let pdf=null,pdfBytes=null,pageNum=1,zoom=1.15,objects=[],selected=null,tool='select',renderToken=0,pageDetected=new Map(),formEdits=new Map();
const stage=$('#stage'),overlay=$('#overlay'),detected=$('#detected'),canvas=$('#pdfCanvas');
const esc=s=>(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function pageObjects(){return objects.filter(o=>o.page===pageNum)}
function setSelected(el){document.querySelectorAll('.obj.selected').forEach(x=>x.classList.remove('selected'));selected=el;if(el)el.classList.add('selected')}
async function scanPage(page,vp){const text=await page.getTextContent();const anns=await page.getAnnotations({intent:'display'});const textItems=[];for(const item of text.items){if(!item.str?.trim())continue;const tx=pdfjsLib.Util.transform(vp.transform,item.transform);const fs=Math.max(6,Math.hypot(tx[2],tx[3]));const w=Math.max(4,item.width*zoom),h=Math.max(8,fs);textItems.push({str:item.str,x:tx[4],y:tx[5]-h,w,h,fontSize:fs/zoom});}
 const fields=anns.filter(a=>a.subtype==='Widget').map(a=>{const r=vp.convertToViewportRectangle(a.rect);return {id:a.id,fieldName:a.fieldName||'',fieldType:a.fieldType||'',value:a.fieldValue??'',options:a.options||[],x:Math.min(r[0],r[2]),y:Math.min(r[1],r[3]),w:Math.abs(r[2]-r[0]),h:Math.abs(r[3]-r[1])}});pageDetected.set(pageNum,{textItems,fields});}
async function render(){if(!pdf)return;const token=++renderToken;const page=await pdf.getPage(pageNum);const vp=page.getViewport({scale:zoom});if(token!==renderToken)return;canvas.width=vp.width;canvas.height=vp.height;for(const el of [canvas,overlay,detected,stage]){el.style.width=vp.width+'px';el.style.height=vp.height+'px'}await page.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise;await scanPage(page,vp);drawDetected();drawObjects();$('#pageInfo').textContent=`Page ${pageNum} / ${pdf.numPages}`;$('#zoomLabel').textContent=Math.round(zoom/1.15*100)+'%'}
function drawDetected(){detected.innerHTML='';const d=pageDetected.get(pageNum)||{textItems:[],fields:[]};$('#detectInfo').textContent=`${d.textItems.length} text pieces • ${d.fields.length} form fields on this page`;
 if($('#showText').checked) d.textItems.forEach((t,i)=>{const el=document.createElement('div');el.className='detText';el.title='Click to replace: '+t.str;Object.assign(el.style,{left:t.x+'px',top:t.y+'px',width:Math.max(t.w,6)+'px',height:Math.max(t.h,8)+'px'});el.onclick=e=>{e.stopPropagation();if(tool!=='select')return;editDetectedText(t,i)};detected.appendChild(el)});
 if($('#showFields').checked)d.fields.forEach(f=>drawField(f));}
function editDetectedText(t,i){if(objects.some(o=>o.type==='replaceText'&&o.page===pageNum&&o.sourceIndex===i)){const o=objects.find(o=>o.type==='replaceText'&&o.page===pageNum&&o.sourceIndex===i);const el=overlay.querySelector(`[data-id="${o.id}"] .textbody`);el?.focus();return}const x=t.x/zoom,y=t.y/zoom,w=Math.max(50,t.w/zoom),h=Math.max(18,t.h/zoom);const o=addObj('replaceText',x,y,{w,h,fontSize:Math.max(7,t.fontSize),text:t.str,sourceIndex:i});setTimeout(()=>{const tb=overlay.querySelector(`[data-id="${o.id}"] .textbody`);if(tb){tb.focus();document.execCommand?.('selectAll',false,null)}},0)}
function fieldKey(f){return `${pageNum}:${f.fieldName||f.id}`}
function drawField(f){const key=fieldKey(f),val=formEdits.has(key)?formEdits.get(key):f.value;let el;if(f.fieldType==='Btn'){el=document.createElement('button');el.className='pdfField checkbox';el.textContent=(val && val!=='Off' && val!==false)?'✓':'';el.onclick=e=>{e.stopPropagation();formEdits.set(key,!el.textContent);el.textContent=el.textContent?'':'✓'}}else if(f.fieldType==='Ch'&&f.options?.length){el=document.createElement('select');el.className='pdfField';for(const op of f.options){const opt=document.createElement('option');opt.value=op.exportValue??op.displayValue??op;opt.textContent=op.displayValue??op.exportValue??op;el.appendChild(opt)}el.value=val||'';el.onchange=()=>formEdits.set(key,el.value)}else{el=document.createElement('input');el.className='pdfField';el.value=val||'';el.oninput=()=>formEdits.set(key,el.value)}el.title=f.fieldName||'PDF form field';Object.assign(el.style,{left:f.x+'px',top:f.y+'px',width:Math.max(f.w,12)+'px',height:Math.max(f.h,12)+'px'});detected.appendChild(el)}
function drawObjects(){overlay.innerHTML='';selected=null;for(const o of pageObjects())createEl(o)}
function createEl(o){const el=document.createElement('div');el.className='obj '+o.type;el.dataset.id=o.id;Object.assign(el.style,{left:o.x*zoom+'px',top:o.y*zoom+'px',width:o.w*zoom+'px',height:o.h*zoom+'px'});if(o.type==='text'||o.type==='replaceText'){el.innerHTML=`<div class="textbody" contenteditable="true">${esc(o.text)}</div><i class="handle"></i>`;el.style.fontSize=o.fontSize*zoom+'px'}if(o.type==='whiteout')el.innerHTML='<i class="handle"></i>';if(o.type==='rect')el.innerHTML='<i class="handle"></i>';if(o.type==='check'){el.innerHTML='<span>✓</span><i class="handle"></i>';el.style.fontSize=o.fontSize*zoom+'px'}if(o.type==='image')el.innerHTML=`<img src="${o.src}"><i class="handle"></i>`;overlay.appendChild(el);wire(el,o);return el}
function wire(el,o){el.addEventListener('pointerdown',e=>{if(e.target.classList.contains('textbody')){setSelected(el);return}if(e.target.classList.contains('handle'))return;setSelected(el);let sx=e.clientX,sy=e.clientY,ox=o.x,oy=o.y;el.setPointerCapture(e.pointerId);const move=ev=>{o.x=ox+(ev.clientX-sx)/zoom;o.y=oy+(ev.clientY-sy)/zoom;el.style.left=o.x*zoom+'px';el.style.top=o.y*zoom+'px'};const up=()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up)};el.addEventListener('pointermove',move);el.addEventListener('pointerup',up)});const h=el.querySelector('.handle');h?.addEventListener('pointerdown',e=>{e.stopPropagation();setSelected(el);let sx=e.clientX,sy=e.clientY,ow=o.w,oh=o.h;h.setPointerCapture(e.pointerId);const move=ev=>{o.w=Math.max(12,ow+(ev.clientX-sx)/zoom);o.h=Math.max(12,oh+(ev.clientY-sy)/zoom);el.style.width=o.w*zoom+'px';el.style.height=o.h*zoom+'px'};const up=()=>{h.removeEventListener('pointermove',move);h.removeEventListener('pointerup',up)};h.addEventListener('pointermove',move);h.addEventListener('pointerup',up)});const tb=el.querySelector('.textbody');tb?.addEventListener('input',()=>o.text=tb.innerText);tb?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();tb.blur()}})}
function addObj(type,x=60,y=60,extra={}){const base={id:crypto.randomUUID(),page:pageNum,type,x,y,w:(type==='text'||type==='replaceText')?180:type==='image'?130:40,h:(type==='text'||type==='replaceText')?34:type==='image'?55:32,fontSize:18,...extra};objects.push(base);const el=createEl(base);setSelected(el);return base}
overlay.addEventListener('pointerdown',e=>{if(e.target!==overlay)return;setSelected(null);const r=overlay.getBoundingClientRect(),x=(e.clientX-r.left)/zoom,y=(e.clientY-r.top)/zoom;if(tool==='text')addObj('text',x,y,{text:'Type here'});if(tool==='whiteout')addObj('whiteout',x,y,{w:160,h:28});if(tool==='rect')addObj('rect',x,y,{w:160,h:40});if(tool==='check')addObj('check',x,y,{w:30,h:30,fontSize:24})});
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b))});$('#showText').onchange=drawDetected;$('#showFields').onchange=drawDetected;
$('#pdfInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;pdfBytes=new Uint8Array(await f.arrayBuffer());pdf=await pdfjsLib.getDocument({data:pdfBytes.slice()}).promise;pageNum=1;objects=[];formEdits.clear();pageDetected.clear();$('#empty').hidden=true;$('#stageWrap').hidden=false;$('#save').disabled=false;render()};
$('#prev').onclick=()=>{if(pdf&&pageNum>1){pageNum--;render()}};$('#next').onclick=()=>{if(pdf&&pageNum<pdf.numPages){pageNum++;render()}};$('#zoomIn').onclick=()=>{if(pdf){zoom=Math.min(2.5,zoom+.15);render()}};$('#zoomOut').onclick=()=>{if(pdf){zoom=Math.max(.5,zoom-.15);render()}};$('#delete').onclick=()=>{if(!selected)return;const id=selected.dataset.id;objects=objects.filter(o=>o.id!==id);selected.remove();selected=null};$('#undo').onclick=()=>{if(objects.length){objects.pop();drawObjects()}};
function dataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}async function addImageFile(file){const src=await dataURL(file);const img=new Image();img.onload=()=>{let w=150,h=w*img.height/img.width;if(h>100){h=100;w=h*img.width/img.height}addObj('image',60,60,{src,w,h})};img.src=src}$('#addImage').onclick=()=>$('#imageInput').click();$('#imageInput').onchange=e=>{if(e.target.files[0])addImageFile(e.target.files[0]);e.target.value=''};
function getPresets(){try{return JSON.parse(localStorage.getItem('pdf-sign-presets')||'[]')}catch{return[]}}function showPresets(){const p=getPresets();$('#presets').innerHTML=p.length?p.map((x,i)=>`<div class="preset"><button data-p="${i}">${esc(x.name)}</button><button data-d="${i}">×</button></div>`).join(''):'<small>No saved presets</small>';document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{const x=getPresets()[+b.dataset.p],img=new Image();img.onload=()=>{let w=150,h=w*img.height/img.width;addObj('image',60,60,{src:x.src,w,h})};img.src=x.src});document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{let a=getPresets();a.splice(+b.dataset.d,1);localStorage.setItem('pdf-sign-presets',JSON.stringify(a));showPresets()})}$('#savePreset').onclick=()=>{const inp=document.createElement('input');inp.type='file';inp.accept='image/png,image/jpeg';inp.onchange=async()=>{if(!inp.files[0])return;const name=prompt('Preset name:',inp.files[0].name.replace(/\.[^.]+$/,''));if(!name)return;const a=getPresets();a.push({name,src:await dataURL(inp.files[0])});localStorage.setItem('pdf-sign-presets',JSON.stringify(a));showPresets()};inp.click()};showPresets();
async function applyFormEdits(doc){let form;try{form=doc.getForm()}catch{return}for(const [key,val] of formEdits){const name=key.slice(key.indexOf(':')+1);let field;try{field=form.getField(name)}catch{continue}try{const type=field.constructor.name;if(type.includes('CheckBox'))val?field.check():field.uncheck();else if(type.includes('RadioGroup'))field.select(String(val));else if(type.includes('Dropdown')||type.includes('OptionList'))field.select(String(val));else if(type.includes('TextField'))field.setText(String(val));}catch(e){console.warn('Could not set field',name,e)}}try{form.updateFieldAppearances(await doc.embedFont(StandardFonts.Helvetica))}catch{}}
$('#save').onclick=async()=>{if(!pdfBytes)return;const doc=await PDFDocument.load(pdfBytes);const font=await doc.embedFont(StandardFonts.Helvetica);await applyFormEdits(doc);for(const o of objects){const p=doc.getPage(o.page-1),H=p.getHeight();if(o.type==='whiteout'||o.type==='replaceText')p.drawRectangle({x:o.x,y:H-o.y-o.h,width:o.w,height:o.h,color:rgb(1,1,1)});if(o.type==='rect')p.drawRectangle({x:o.x,y:H-o.y-o.h,width:o.w,height:o.h,borderColor:rgb(0,0,0),borderWidth:1});if(o.type==='text'||o.type==='replaceText')p.drawText(o.text||'',{x:o.x,y:H-o.y-o.fontSize,width:o.w,size:o.fontSize,font,color:rgb(0,0,0),lineHeight:o.fontSize*1.15,maxWidth:o.w});if(o.type==='check')p.drawText('X',{x:o.x+4,y:H-o.y-o.fontSize,size:o.fontSize,font,color:rgb(0,0,0)});if(o.type==='image'){const bytes=await fetch(o.src).then(r=>r.arrayBuffer());let im;try{im=await doc.embedPng(bytes)}catch{im=await doc.embedJpg(bytes)}p.drawImage(im,{x:o.x,y:H-o.y-o.h,width:o.w,height:o.h})}}const out=await doc.save();const blob=new Blob([out],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='edited.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
window.addEventListener('keydown',e=>{if((e.key==='Delete'||e.key==='Backspace')&&selected&&!e.target.isContentEditable&&!['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();$('#delete').click()}});
